trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:

    Python311:
      python.version: '3.11'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip cache purge  # Limpar cache do pip
  displayName: 'Install dependencies and clean pip cache'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run pytest'
